services:
  firebird:
    image: firebirdsql/firebird
    restart: always
    environment:
      - FIREBIRD_ROOT_PASSWORD=maria
      - FIREBIRD_USER=maria
      - FIREBIRD_PASSWORD=mariita
      - FIREBIRD_DATABASE=mirror.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
    volumes:
      - ./data:/var/lib/firebird/data
      - ./scripts:/opt/firebird/db_scripts


    ports:
    - 3050:3050

